// Tests INV-001 (and PRH-002 syntax armor lives in ProhibitionTests.cs):
// exact-pin, source-controlled restore of the whole toolchain.
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using Corrected.Spike.Contracts;
using Xunit;

namespace Corrected.Spike.Tests;

public class Inv001ToolchainPinTests
{
    // Tests INV-001 [unit]: every Dafny*/Boogie.* package in every project's
    // resolved graph is exact-pinned, with a committed packages.lock.json per project.
    // Source: spikes/dafny-compat/adapters/SpikeDafnyAdapter.RouteA/packages.lock.json
    // (real producer output: generated by `dotnet restore` at the pinned SDK, committed in-repo — AP-014).
    [Fact]
    public void LockFiles_ExistPerProject_AndPinDafnyBoogieFamilyExactly()
    {
        foreach (var (name, _) in SpikePaths.Projects)
        {
            var lockPath = SpikePaths.LockFilePath(name);
            Assert.True(File.Exists(lockPath), $"missing committed packages.lock.json for {name} (INV-001)");

            using var doc = SpikePaths.Json(lockPath);
            foreach (var fw in doc.RootElement.GetProperty("dependencies").EnumerateObject())
            {
                foreach (var dep in fw.Value.EnumerateObject())
                {
                    var id = dep.Name;
                    var isDafny = id.StartsWith("Dafny", StringComparison.Ordinal);
                    var isBoogie = id.StartsWith("Boogie.", StringComparison.Ordinal);
                    if (!isDafny && !isBoogie)
                    {
                        continue;
                    }

                    var resolved = dep.Value.GetProperty("resolved").GetString();
                    var expectedFamilyVersion = isDafny ? "4.11.0" : "3.5.5";
                    Assert.True(resolved == expectedFamilyVersion,
                        $"{name}/{fw.Name}: {id} resolved {resolved}, expected {expectedFamilyVersion} (INV-001: no member of the family may float off-pin)");
                }
            }
        }

        // The four spec-named pins must be present in the seam graphs they anchor.
        AssertLockContains("SpikeDafnyAdapter.RouteA", "DafnyDriver", "4.11.0");
        AssertLockContains("SpikeDafnyAdapter.RouteA", "DafnyCore", "4.11.0");
        AssertLockContains("SpikeDafnyAdapter.RouteB", "DafnyCore", "4.11.0");
        AssertLockContains("SpikeDafnyAdapter.RouteB", "DafnyPipeline", "4.11.0");
        AssertLockContains("SpikeDafnyAdapter.RouteB", "Boogie.ExecutionEngine", "3.5.5");
    }

    private static void AssertLockContains(string project, string package, string version)
    {
        using var doc = SpikePaths.Json(SpikePaths.LockFilePath(project));
        var found = false;
        foreach (var fw in doc.RootElement.GetProperty("dependencies").EnumerateObject())
        {
            if (fw.Value.TryGetProperty(package, out var dep))
            {
                found = true;
                Assert.Equal(version, dep.GetProperty("resolved").GetString());
            }
        }
        Assert.True(found, $"{project} lock must contain {package} (DD-001 route graph)");
    }

    // Tests INV-001 [unit]: spike-local NuGet.Config with <clear/>, nuget.org
    // as sole source, and package source mapping.
    [Fact]
    public void NuGetConfig_ClearSingleSourceAndMapping()
    {
        var doc = SpikePaths.Xml(SpikePaths.P("NuGet.Config"));
        var sources = doc.Root!.Element("packageSources")!;
        Assert.NotNull(sources.Element("clear"));
        var adds = sources.Elements("add").ToList();
        Assert.Single(adds);
        Assert.Equal("https://api.nuget.org/v3/index.json", adds[0].Attribute("value")!.Value);

        var mapping = doc.Root!.Element("packageSourceMapping");
        Assert.NotNull(mapping);
        var mapSource = mapping!.Elements("packageSource").Single();
        Assert.Equal("nuget.org", mapSource.Attribute("key")!.Value);
    }

    // Tests INV-001/EA-001 [unit]: committed global.json pins one exact .NET 10
    // SDK with rollForward: disable and allowPrerelease: false.
    [Fact]
    public void GlobalJson_ExactSdkPin_NoRollForward_NoPrerelease()
    {
        using var doc = SpikePaths.Json(SpikePaths.P("global.json"));
        var sdk = doc.RootElement.GetProperty("sdk");
        Assert.Equal(SpecConstants.SdkPin, sdk.GetProperty("version").GetString());
        Assert.Equal("disable", sdk.GetProperty("rollForward").GetString());
        Assert.False(sdk.GetProperty("allowPrerelease").GetBoolean());
    }

    // Tests INV-001 [unit] (codex R2-6/R3-8): CPM authoritative with the exact
    // properties, including CentralPackageVersionOverrideEnabled=false.
    [Fact]
    public void CentralPackageManagement_AuthoritativeProperties()
    {
        var doc = SpikePaths.Xml(SpikePaths.P("Directory.Packages.props"));
        string Prop(string name) => doc.Descendants(name).Single().Value.Trim();
        Assert.Equal("true", Prop("ManagePackageVersionsCentrally"));
        Assert.Equal("true", Prop("CentralPackageTransitivePinningEnabled"));
        Assert.Equal("false", Prop("CentralPackageVersionOverrideEnabled"));
    }

    // Tests INV-001 [unit] (codex F9): exact singleton-range constraints on
    // every PackageVersion — plain Version="4.11.0" is a minimum-inclusive range.
    [Fact]
    public void AllPackageVersions_AreExactSingletonRanges()
    {
        var doc = SpikePaths.Xml(SpikePaths.P("Directory.Packages.props"));
        var versions = doc.Descendants("PackageVersion").ToList();
        Assert.NotEmpty(versions);
        foreach (var pv in versions)
        {
            var v = pv.Attribute("Version")!.Value;
            Assert.Matches(@"^\[[^,\[\]]+\]$", v);
        }
        // The three spec-named singleton pins, verbatim.
        string PinOf(string id) => versions.Single(p => p.Attribute("Include")!.Value == id).Attribute("Version")!.Value;
        Assert.Equal("[4.11.0]", PinOf("DafnyCore"));
        Assert.Equal("[4.11.0]", PinOf("DafnyPipeline"));
        Assert.Equal("[4.11.0]", PinOf("DafnyDriver"));
        Assert.Equal("[3.5.5]", PinOf("Boogie.ExecutionEngine"));
        Assert.Equal("[2.0.0-beta4.22272.1]", PinOf("System.CommandLine"));
    }

    // Tests INV-001 [unit] (codex R3-8): a scan rejecting any VersionOverride attribute.
    [Fact]
    public void NoVersionOverrideAttribute_InAnyProjectOrProps()
    {
        var files = SpikePaths.AllCsprojFiles().Append(SpikePaths.P("Directory.Packages.props"));
        foreach (var file in files)
        {
            var doc = SpikePaths.Xml(file);
            var offenders = doc.Descendants().Attributes("VersionOverride").ToList();
            Assert.True(offenders.Count == 0, $"VersionOverride attribute found in {file} (INV-001 prohibits overrides)");
        }
    }

    // Tests INV-001 [unit]: PackageReference items are versionless (CPM is authoritative).
    [Fact]
    public void PackageReferences_AreVersionless()
    {
        foreach (var file in SpikePaths.AllCsprojFiles())
        {
            var doc = SpikePaths.Xml(file);
            foreach (var pr in doc.Descendants("PackageReference"))
            {
                Assert.True(pr.Attribute("Version") is null && pr.Element("Version") is null,
                    $"versioned PackageReference in {file}: {pr}");
            }
        }
    }

    // Tests INV-001 [unit] (codex F9): spike-local sealing files terminate
    // MSBuild upward inheritance; Directory.Packages.props is non-empty and authoritative.
    [Fact]
    public void SealingFiles_Present_AndPackagesPropsNonEmptyAuthoritative()
    {
        Assert.True(File.Exists(SpikePaths.P("Directory.Build.props")), "missing Directory.Build.props sealing file");
        Assert.True(File.Exists(SpikePaths.P("Directory.Build.targets")), "missing Directory.Build.targets sealing file");
        Assert.True(File.Exists(SpikePaths.P("Directory.Build.rsp")), "missing Directory.Build.rsp sealing file");
        var packagesProps = SpikePaths.Xml(SpikePaths.P("Directory.Packages.props"));
        Assert.NotEmpty(packagesProps.Descendants("PackageVersion"));

        // RestorePackagesWithLockFile + locked-mode restore are enabled spike-wide.
        var buildProps = File.ReadAllText(SpikePaths.P("Directory.Build.props"));
        Assert.Contains("<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>", buildProps);
        Assert.Contains("RestoreLockedMode", buildProps);
        Assert.Contains("NU1605", buildProps); // downgrade warnings as errors
    }

    // Tests INV-001 [integration] (RS-014a, codex F9, AP-011, TA-B3a):
    // behavioral stale-lock negative test with TEST-owned fault construction.
    // The TEST copies the Route A project graph + sealing/config files into
    // scratch, runs ONE GENERIC restore phase (control leg) which must SUCCEED,
    // then the TEST ITSELF edits the lock JSON (DafnyCore -> nightly), verifies
    // the mutation landed on disk, and re-runs the IDENTICAL generic phase —
    // which must fail with the locked-mode mismatch diagnostic (NU1004-class).
    // Any-failure (network, missing package) cannot satisfy this: the control
    // leg already proved the same phase succeeds on the pristine copy.
    [Fact]
    public void StaleLockMutation_TestEditedLock_FailsWithNU1004_AfterSuccessfulControlRestore()
    {
        var scratch = SpikePaths.TestScratch("inv001-stale-lock");

        // TEST-owned scratch copy: sealing/config roots + contracts + Route A seam.
        foreach (var rootFile in new[] { "NuGet.Config", "global.json", "Directory.Packages.props", "Directory.Build.props", "Directory.Build.targets", "Directory.Build.rsp" })
        {
            File.Copy(SpikePaths.P(rootFile), Path.Combine(scratch, rootFile), overwrite: true);
        }
        SpikePaths.CopyTree(SpikePaths.P("contracts"), Path.Combine(scratch, "contracts"));
        SpikePaths.CopyTree(SpikePaths.P("adapters", "SpikeDafnyAdapter.RouteA"), Path.Combine(scratch, "adapters", "SpikeDafnyAdapter.RouteA"));
        var scratchProj = Path.Combine(scratch, "adapters", "SpikeDafnyAdapter.RouteA", "SpikeDafnyAdapter.RouteA.csproj");
        var scratchLock = Path.Combine(scratch, "adapters", "SpikeDafnyAdapter.RouteA", "packages.lock.json");

        // Phase 1 — CONTROL: the generic restore phase on the pristine copy must SUCCEED.
        var control = Launch.Script("scripts/run-spike.sh", null, "--phase", "restore", "--project", scratchProj);
        Assert.True(control.ExitCode == 0,
            $"control restore failed (exit {control.ExitCode}); an already-broken restore cannot prove locked mode. stderr: {control.StdErr}");

        // Phase 2 — the TEST mutates ONLY the lock-consistency data. TEST_BUG
        // fix #5 (endorsed): mutate the REQUESTED range for DafnyCore (a
        // lock-vs-project-declaration inconsistency, the canonical
        // deterministic offline NU1004 trigger, proving lock VALIDATION was in
        // effect — RS-014a), bumping resolved alongside so the lock stays
        // self-consistent while disagreeing with the project's pin.
        const string nightly = "4.11.1-nightly-2026-01-01";
        var mutated = MutateDafnyCoreRequestedRange(File.ReadAllText(scratchLock), nightly);
        File.WriteAllText(scratchLock, mutated);
        Assert.Contains(nightly, File.ReadAllText(scratchLock)); // the fault really landed on disk (TA-B3a)

        // Phase 3 — the IDENTICAL generic phase must now fail with the
        // locked-mode mismatch diagnostic. NU1004 ONLY: NU1102-class
        // missing-package failures are the spec-excluded any-failure shape.
        var negative = Launch.Script("scripts/run-spike.sh", null, "--phase", "restore", "--project", scratchProj);
        Assert.NotEqual(0, negative.ExitCode);
        Assert.Contains("NU1004", negative.StdOut + negative.StdErr);
    }

    private static string MutateDafnyCoreRequestedRange(string lockJson, string nightlyVersion)
    {
        var nightlyRange = $"[{nightlyVersion}, {nightlyVersion}]";
        using var doc = System.Text.Json.JsonDocument.Parse(lockJson);
        using var stream = new MemoryStream();
        using (var writer = new System.Text.Json.Utf8JsonWriter(stream, new System.Text.Json.JsonWriterOptions { Indented = true }))
        {
            void WriteElement(System.Text.Json.JsonElement el, bool insideDafnyCore)
            {
                switch (el.ValueKind)
                {
                    case System.Text.Json.JsonValueKind.Object:
                        writer.WriteStartObject();
                        foreach (var prop in el.EnumerateObject())
                        {
                            writer.WritePropertyName(prop.Name);
                            if (insideDafnyCore && prop.Name == "requested")
                            {
                                writer.WriteStringValue(nightlyRange);
                            }
                            else if (insideDafnyCore && prop.Name == "resolved")
                            {
                                writer.WriteStringValue(nightlyVersion);
                            }
                            else
                            {
                                WriteElement(prop.Value, insideDafnyCore || prop.Name == "DafnyCore");
                            }
                        }
                        writer.WriteEndObject();
                        break;
                    case System.Text.Json.JsonValueKind.Array:
                        writer.WriteStartArray();
                        foreach (var item in el.EnumerateArray()) { WriteElement(item, insideDafnyCore); }
                        writer.WriteEndArray();
                        break;
                    default:
                        el.WriteTo(writer);
                        break;
                }
            }
            WriteElement(doc.RootElement, insideDafnyCore: false);
        }
        return System.Text.Encoding.UTF8.GetString(stream.ToArray());
    }

    // Tests INV-001 [integration] (TA-B3b): the effective build inherits no
    // props from above the spike root — proven against the RESOLVED IMPORT
    // LIST, parsed and judged BY THE TEST, not by a script-emitted OK marker.
    [Fact]
    public void EffectiveBuild_InheritsNoPropsAboveSpikeRoot()
    {
        var result = Launch.Script("scripts/run-spike.sh", null, "--phase", "preprocess-audit");
        Assert.True(result.ExitCode == 0, $"preprocess audit failed: {result.StdErr}");

        var imports = result.StdOut.Split('\n')
            .Where(l => l.StartsWith("IMPORT ", StringComparison.Ordinal))
            .Select(l => l["IMPORT ".Length..].Trim())
            .ToList();
        Assert.True(imports.Count > 0, "preprocess audit emitted no IMPORT lines — nothing was audited (AP-010)");

        var repoRoot = Path.GetFullPath(SpikePaths.RepoRoot) + Path.DirectorySeparatorChar;
        var spikeRoot = Path.GetFullPath(SpikePaths.SpikeRoot) + Path.DirectorySeparatorChar;
        foreach (var import in imports)
        {
            var full = Path.GetFullPath(import);
            var insideRepo = full.StartsWith(repoRoot, StringComparison.Ordinal);
            var insideSpike = full.StartsWith(spikeRoot, StringComparison.Ordinal);
            Assert.False(insideRepo && !insideSpike,
                $"MSBuild import leaks from above the spike root: {import} (INV-001 sealing violated)");
        }
    }
}
