#!/usr/bin/env bash
# scripts/clean-runs.sh — operator disk-reclaim tool for the untracked out/ area
# (MA-UX-2/MA-RB-1). Each canonical run retains an ~1GB out/<run_id>/ root
# (package-cache copy + extracted net8 runtime + z3 archive + build output); a
# long-lived dev tree accumulates many. This tool prunes old run roots
# (out/runid-*) and regen products (out/regen-*), keeping the newest N by mtime.
# It NEVER touches out/current (the dev-loop pointer) or out/cache (the shared
# package/archive cache) — deleting a run root is always safe (run products are
# regenerated by the next controller run).
#
# The bootstrap controller itself also prunes out/runid-* (keep newest 5) at the
# start of every CANONICAL run; this script is the explicit, on-demand operator
# form and can prune more aggressively.
#
# Invocation (hardened, per PRH-004):
#   env -i HOME="$HOME" bash -p scripts/clean-runs.sh [--keep N] [--out-dir DIR]
#     --keep N      keep the newest N run/regen roots (default 3)
#     --out-dir DIR prune under DIR instead of the default out/ (test isolation;
#                   operators never need it)
#
# Exit codes:
#   0   pruned (or nothing to prune) — no report is emitted (this is a
#       maintenance tool, not a run)
#   20  usage error / unhardened invocation
ALLOWLIST=(bash dotnet curl sha256sum tar unzip git mkdir mktemp mv rm chmod setsid kill sleep)

run_cmd() {
  local cmd="$1"; shift
  local base="${cmd##*/}"
  local ok=""
  local allowed
  for allowed in "${ALLOWLIST[@]}"; do
    if [ "$base" = "$allowed" ]; then ok=1; fi
  done
  if [ -z "$ok" ]; then
    echo "clean-runs: DENY non-allowlisted command: $cmd (PRH-004)" >&2
    exit 20
  fi
  command "$cmd" "$@"
}

case "$-" in
  *p*) : ;;
  *)
    echo "clean-runs: refusing the unhardened invocation — use: env -i HOME=\"\$HOME\" bash -p scripts/clean-runs.sh (PRH-004)" >&2
    exit 20 ;;
esac

set -euo pipefail
PATH="/usr/bin:/bin"
export PATH

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SPIKE_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
OUT_DIR="$SPIKE_ROOT/out"

KEEP=3
while [ $# -gt 0 ]; do
  case "$1" in
    --keep) KEEP="$2"; shift 2 ;;
    --out-dir) OUT_DIR="$2"; shift 2 ;;
    *) echo "clean-runs: unknown argument '$1' (usage: clean-runs.sh [--keep N] [--out-dir DIR])" >&2; exit 20 ;;
  esac
done
case "$KEEP" in
  ''|*[!0-9]*) echo "clean-runs: --keep must be a positive integer (usage: clean-runs.sh [--keep N] [--out-dir DIR])" >&2; exit 20 ;;
esac
# MA-RB-R2-4: --keep 0 is refused — a keep-0 sweep would delete the out/current
# referent (and every root) with no survivor; prune must retain at least one.
if [ "$KEEP" -eq 0 ]; then
  echo "clean-runs: --keep 0 refused — prune must retain at least one root (never the out/current target) (MA-RB-R2-4)" >&2
  exit 20
fi

if [ ! -d "$OUT_DIR" ]; then
  echo "clean-runs: nothing to prune ($OUT_DIR does not exist)" >&2
  exit 0
fi

# MA-RB-R2-4: resolve the run root the out/current pointer TARGETS and add it to
# the protect set — a keep-N sweep must NEVER dangle the dev-loop pointer. Reads
# out/current/spike.runsettings's SPIKE_RUN_CONTEXT (<run-root>/run-context.json)
# and strips the file name. The comment/message "untouched" means the out/current
# and out/cache DIRECTORIES and now the pointer's TARGET, backed by this skip.
REFERENT=""
RUNSETTINGS="$OUT_DIR/current/spike.runsettings"
if [ -f "$RUNSETTINGS" ]; then
  while IFS= read -r line; do
    case "$line" in
      *'<SPIKE_RUN_CONTEXT>'*'</SPIKE_RUN_CONTEXT>'*)
        ctx="${line#*<SPIKE_RUN_CONTEXT>}"
        ctx="${ctx%%</SPIKE_RUN_CONTEXT>*}"
        REFERENT="${ctx%/run-context.json}"
        break ;;
    esac
  done < "$RUNSETTINGS"
fi

# Candidate roots: run roots + regen products, NEVER out/current, out/cache, or
# the out/current pointer's target (REFERENT).
dirs=()
for d in "$OUT_DIR"/runid-* "$OUT_DIR"/regen-*; do
  [ -d "$d" ] || continue
  case "$d" in
    "$OUT_DIR"/current|"$OUT_DIR"/cache) continue ;;
  esac
  [ -n "$REFERENT" ] && [ "$d" = "$REFERENT" ] && continue
  dirs+=("$d")
done

removed=0
for d in "${dirs[@]}"; do
  newer=0
  for other in "${dirs[@]}"; do
    [ "$other" = "$d" ] && continue
    [ "$other" -nt "$d" ] && newer=$((newer + 1))
  done
  if [ "$newer" -ge "$KEEP" ]; then
    run_cmd rm -rf -- "$d"
    removed=$((removed + 1))
  fi
done

# MA-UX-R2-1: reclaim out/test-scratch — the LARGEST consumer (nested-controller
# fixture roots, ~10GB on a long-lived tree), unreachable by the runid-*/regen-*
# sweep. Keep only the newest token dir (a concurrent suite's), delete the rest.
# Also drop loose out/preprocess.*.xml (MSBuild dumps) and out/*.log stragglers.
scratch_removed=0
SCRATCH_DIR="$OUT_DIR/test-scratch"
if [ -d "$SCRATCH_DIR" ]; then
  tokens=()
  for t in "$SCRATCH_DIR"/*; do
    [ -d "$t" ] || continue
    tokens+=("$t")
  done
  for t in "${tokens[@]}"; do
    newer=0
    for other in "${tokens[@]}"; do
      [ "$other" = "$t" ] && continue
      [ "$other" -nt "$t" ] && newer=$((newer + 1))
    done
    # keep only the newest (newer==0); delete every older token dir.
    if [ "$newer" -ge 1 ]; then
      run_cmd rm -rf -- "$t"
      scratch_removed=$((scratch_removed + 1))
    fi
  done
fi
loose_removed=0
for f in "$OUT_DIR"/preprocess.*.xml "$OUT_DIR"/*.log; do
  [ -f "$f" ] || continue
  run_cmd rm -f -- "$f"
  loose_removed=$((loose_removed + 1))
done

echo "clean-runs: kept the newest $KEEP run/regen root(s); removed $removed old root(s), $scratch_removed stale test-scratch token dir(s), and $loose_removed loose file(s) under $OUT_DIR (the out/current and out/cache directories, and the out/current pointer's target, are untouched)." >&2
exit 0
